#!/usr/bin/env bash
# check_firebase_config.sh
#
# Pre-build safety check: exits 1 if firebase_options.dart is missing.
# Run before `flutter build` in CI or locally.
#
# Usage:
#   bash scripts/check_firebase_config.sh
#   bash scripts/check_firebase_config.sh --example   # also checks .example file

set -euo pipefail

FIREBASE_OPTS="frontend/lib/firebase_options.dart"
FIREBASE_EXAMPLE="frontend/lib/firebase_options.dart.example"

echo "[check_firebase_config] Checking Firebase configuration..."

if [[ ! -f "$FIREBASE_OPTS" ]]; then
  echo ""
  echo "ERROR: $FIREBASE_OPTS not found."
  echo ""
  echo "  SafePulse requires a real firebase_options.dart generated by the"
  echo "  Firebase CLI ('flutterfire configure') before building."
  echo ""
  echo "  Steps:"
  echo "    1. Install FlutterFire CLI:  dart pub global activate flutterfire_cli"
  echo "    2. Run:                      flutterfire configure"
  echo "    3. Copy the generated file:  frontend/lib/firebase_options.dart"
  echo ""
  echo "  A placeholder template is at: $FIREBASE_EXAMPLE"
  echo ""
  exit 1
fi

# Sanity-check: the real file should not contain placeholder values
if grep -q "YOUR_.*_API_KEY" "$FIREBASE_OPTS" 2>/dev/null; then
  echo ""
  echo "ERROR: $FIREBASE_OPTS appears to contain placeholder values."
  echo "  Replace all 'YOUR_*' strings with real Firebase project credentials."
  echo ""
  exit 1
fi

if [[ "${1:-}" == "--example" ]]; then
  if [[ ! -f "$FIREBASE_EXAMPLE" ]]; then
    echo "ERROR: $FIREBASE_EXAMPLE not found."
    exit 1
  fi
  echo "[check_firebase_config] firebase_options.dart.example present."
fi

echo "[check_firebase_config] OK — firebase_options.dart is present and non-placeholder."
